png("plot3.png")
hpc<-read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings=c("?", "NA"))
hpc$Date<-as.Date(hpc$Date, "%d/%m/%Y")
h<-hpc[hpc$Date >= as.Date("2007-02-01") & hpc$Date <= as.Date("2007-02-02"),]
h$dt<-as.POSIXct(paste(h$Date, h$Time), format="%Y-%m-%d %H:%M:%S")
plot(h$dt, h$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(h$dt, h$Sub_metering_2, col="red")
lines(h$dt, h$Sub_metering_3, col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"), lwd=1)
dev.off()